# Generated by Django 2.1.7 on 2019-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cronjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_time', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'cronjob content',
                'verbose_name_plural': 'article content',
            },
        ),
    ]
