# Generated by Django 2.1.7 on 2019-04-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multitask', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjob',
            options={'verbose_name': 'cronjob content', 'verbose_name_plural': 'cronjob content'},
        ),
    ]
