# Generated by Django 2.1.7 on 2019-04-19 14:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1024)),
                ('address', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('photo_url', models.CharField(max_length=255)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.Website')),
            ],
            options={
                'verbose_name': 'article content',
                'verbose_name_plural': 'article content',
            },
        ),
    ]
